version: '3.8'

services:
  order-service:
    build:
      context: ./order-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: order-service
    ports:
      - "8081:8081"
      - "9001:9001"
    environment:
      QUARKUS_HTTP_PORT: 8081
      QUARKUS_GRPC_SERVER_PORT: 9001
    networks:
      - logistics-network
    depends_on:
      - warehouse-service
      - delivery-service
      - notification-service

  warehouse-service:
    build:
      context: ./warehouse-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: warehouse-service
    ports:
      - "8082:8082"
      - "9002:9002"
    environment:
      QUARKUS_HTTP_PORT: 8082
      QUARKUS_GRPC_SERVER_PORT: 9002
    networks:
      - logistics-network

  delivery-service:
    build:
      context: ./delivery-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: delivery-service
    ports:
      - "8083:8083"
      - "9003:9003"
    environment:
      QUARKUS_HTTP_PORT: 8083
      QUARKUS_GRPC_SERVER_PORT: 9003
    networks:
      - logistics-network
    depends_on:
      - notification-service

  notification-service:
    build:
      context: ./notification-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: notification-service
    ports:
      - "8084:8084"
    environment:
      QUARKUS_HTTP_PORT: 8084
    networks:
      - logistics-network

networks:
  logistics-network:
    driver: bridge
